name: CD

on:
  push:
      paths:
      - 'public/**'
      - 'src/**/*.js'

jobs:
  gh-pages:
    name: GitHub Pages
    runs-on: ubuntu-16.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build & Deploy
      run: ./deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
